[package]
name = "request"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
reqwest = { version= "0.12.4", features = ["json", "blocking"]}
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
